# Generated by Django 3.2 on 2021-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krakenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ready',
            field=models.BooleanField(default=False, help_text="Cochez cette case si vous avez terminé de revendiquer des territoires et que vous êtes prêt à jouer.<br>Cette option n'a plus d'effet une fois la partie démarrée.", verbose_name='prêt à jouer'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='weight',
            field=models.SmallIntegerField(default=0, verbose_name='poids'),
        ),
    ]
