# Generated by Django 3.2 on 2021-04-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krakenapp', '0002_weight_and_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'joueur', 'verbose_name_plural': 'joueurs'},
        ),
        migrations.RemoveField(
            model_name='territory',
            name='owner',
        ),
        migrations.AddField(
            model_name='territory',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory', to='krakenapp.claim', verbose_name='revendication'),
        ),
        migrations.AlterField(
            model_name='action',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='joueur'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='joueur'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to=settings.AUTH_USER_MODEL, verbose_name='joueur'),
        ),
    ]
