# Generated by Django 3.2 on 2021-04-26 18:53

import common.fields
import common.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krakenapp', '0004_player_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='extra',
            field=common.fields.JsonField(blank=True, decoder=common.utils.JsonDecoder, default=dict, encoder=common.utils.JsonEncoder, verbose_name='extra'),
        ),
        migrations.AddField(
            model_name='territory',
            name='extra',
            field=common.fields.JsonField(blank=True, decoder=common.utils.JsonDecoder, default=dict, encoder=common.utils.JsonEncoder, verbose_name='extra'),
        ),
    ]
