# Generated by Django 3.2 on 2021-04-27 16:13

from django.db import migrations


def remove_data(apps, schema_editor):
    from common.models import ContentType, Global, History
    from krakenapp.models import Player
    content_type = ContentType.objects.get_for_model(Player)
    Global.objects.filter(content_type=content_type)
    History.objects.filter(content_type=content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('krakenapp', '0005_player_and_territory_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='modification_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='uuid',
        ),
        migrations.RunPython(remove_data, reverse_code=migrations.RunPython.noop),
    ]
