# Generated by Django 3.2 on 2021-05-03 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krakenapp', '0007_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_money', models.PositiveSmallIntegerField(default=0, verbose_name='argent envoyé')),
                ('sender_troops', models.PositiveSmallIntegerField(default=0, verbose_name='troupes envoyées')),
                ('receiver_money', models.PositiveSmallIntegerField(default=0, verbose_name='argent reçu')),
                ('receiver_troops', models.PositiveSmallIntegerField(default=0, verbose_name='troupes reçues')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date de proposition')),
                ('accepted', models.BooleanField(null=True, verbose_name='accepté')),
                ('done', models.BooleanField(default=False, verbose_name='traité')),
                ('receiver', models.ForeignKey(help_text="Le destinataire ne peut être qu'un joueur avec qui vous avez des frontières communes.", on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'échange',
                'verbose_name_plural': 'échanges',
            },
        ),
    ]
