# Generated by Django 3.2.2 on 2021-05-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krakenapp', '0008_exchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'action', 'verbose_name_plural': 'actions'},
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'verbose_name': 'revendication', 'verbose_name_plural': 'revendications'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'joueur', 'verbose_name_plural': 'joueurs'},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name': 'territoire', 'verbose_name_plural': 'territoires'},
        ),
    ]
